# Generated by Django 2.0.2 on 2020-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('transaction_status', models.CharField(max_length=50)),
                ('total_log', models.CharField(max_length=50)),
                ('kpi', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
