# Generated by Django 2.0.2 on 2020-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_log',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
